spring:
  application:
    name: mall-gateway

server:
  port: 8088

jwt:
  secret: "kubemall-super-secret-key-for-jwt-256bit-example!"
  expiration-ms: 3600000

logging:
  level:
    com.kubemall.gateway: DEBUG
    org.springframework.cloud.gateway: WARN
    org.springframework.web: WARN
    reactor.netty: WARN

  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"