version: "3.8"

services:

  # =========================
  # PostgreSQL
  # =========================
  postgres:
    image: postgres:15
    container_name: kubemall-postgres
    restart: always
    environment:
      POSTGRES_DB: kubemall
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    networks:
      - kubemall-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # =========================
  # mall-user
  # =========================
  mall-user:
    build:
      context: ./mall-user
    container_name: kubemall-user
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - kubemall-net

  # =========================
  # mall-product
  # =========================
  mall-product:
    build:
      context: ./mall-product
    container_name: kubemall-product
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - kubemall-net

  # =========================
  # gateway
  # =========================
  mall-gateway:
    build:
      context: ./mall-gateway
    container_name: kubemall-gateway
    ports:
      - "8088:8088"
    depends_on:
      - mall-user
      - mall-product
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - kubemall-net

# =========================
# network
# =========================
networks:
  kubemall-net:
    driver: bridge

# =========================
# volume
# =========================
volumes:
  postgres_data: