spring:
  application:
    name: mall-user

server:
  port: 8081

jwt:
  secret: "kubemall-super-secret-key-for-jwt-256bit-example!"
  expiration-ms: 3600000

logging:
  level:
    root: INFO
    com.kubemall.user: DEBUG
    # common-web 模块（重要！）
    com.kubemall.web: INFO          # 整个 web 公共模块
    com.kubemall.web.filter: DEBUG  # 具体到 filter，更详细
    # 第三方框架
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"