spring:
  application:
    name: mall-user
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/kubemall?currentSchema=user_schema
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
server:
  port: 8080
  # 中文编码设置
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# JWT 配置
jwt:
  secret: "kubemall-super-secret-key-for-jwt-256bit-example!"
  expiration-ms: 3600000

# 日志配置
logging:
  level:
    root: INFO
    com.kubemall.user: DEBUG
    com.kubemall.user.filter: DEBUG
    com.kubemall.user.aspect: INFO
    org.springframework.security: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%X{traceId}] [%X{username}] %-5level %logger{36} - %msg%n"
  file:
    path: E:/logs/kubemall/mall-user
    name: E:/logs/kubemall/mall-user/mall-user.log
  logback:
    rollingpolicy:
      max-history: 30

