spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/kubemall?currentSchema=product_schema
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: product_schema
    show-sql: false

  sql:
    init:
      mode: always
      continue-on-error: true

logging:
  file:
    path: /var/log/mall-product
    name: /var/log/mall-product/mall-product.log