spring:
  application:
    name: mall-product
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://postgres:5432/kubemall?currentSchema=product_schema
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
server:
  port: 8082
  # 中文编码设置
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 日志配置
logging:
  level:
    root: INFO
    com.kubemall.product: DEBUG
    com.kubemall.product.filter: DEBUG
    com.kubemall.product.aspect: INFO
    # common-web 模块（重要！）
    com.kubemall.web: INFO          # 整个 web 公共模块
    com.kubemall.web.filter: DEBUG  # 具体到 filter，更详细
    # 第三方框架
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
  file:
    path: E:/logs/kubemall/mall-product
    name: E:/logs/kubemall/mall-product/mall-product.log
  logback:
    rollingpolicy:
      max-history: 30

